# Generated by Django 5.1.6 on 2025-03-19 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="profile",
            name="profile_picture",
        ),
        migrations.AlterField(
            model_name="profile",
            name="address",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
