# Generated by Django 5.1.6 on 2025-03-19 17:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0002_remove_profile_profile_picture_alter_profile_address"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="profile",
            name="address",
        ),
    ]
