# Generated by Django 5.1.6 on 2025-03-22 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0004_systemmessage"),
    ]

    operations = [
        migrations.CreateModel(
            name="Message",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("message_type", models.CharField(max_length=50)),
                ("content", models.TextField()),
            ],
        ),
        migrations.AlterField(
            model_name="systemmessage",
            name="key",
            field=models.CharField(max_length=10, unique=True),
        ),
    ]
