# Generated by Django 5.1.6 on 2025-03-22 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0005_message_alter_systemmessage_key"),
    ]

    operations = [
        migrations.AddField(
            model_name="donation",
            name="exp_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="donation",
            name="image",
            field=models.ImageField(
                blank=True, null=True, upload_to="donation_images/"
            ),
        ),
        migrations.AddField(
            model_name="donation",
            name="mfg_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="donation",
            name="item_name",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="donation",
            name="quantity",
            field=models.IntegerField(),
        ),
    ]
