# Generated by Django 5.1.6 on 2025-03-22 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0006_donation_exp_date_donation_image_donation_mfg_date_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="donation",
            name="status",
            field=models.CharField(
                choices=[
                    ("sent", "Request Sent"),
                    ("accepted", "Request Accepted"),
                    ("received", "Donation Received"),
                ],
                default="sent",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="donation",
            name="description",
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name="donation",
            name="quantity",
            field=models.PositiveIntegerField(),
        ),
    ]
