# Generated by Django 5.1.6 on 2025-03-23 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0007_donation_status_alter_donation_description_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="mobile_number",
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
