# Generated by Django 5.1.6 on 2025-04-03 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0010_rename_name_ngo_organization_name_ngo_contact_person_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="address",
            field=models.TextField(default="Not Provided"),
            preserve_default=False,
        ),
    ]
