# Generated by Django 5.1.6 on 2025-04-03 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0011_profile_address"),
    ]

    operations = [
        migrations.AddField(
            model_name="donation",
            name="address",
            field=models.TextField(blank=True, null=True),
        ),
    ]
